GET http://localhost:8000/kk

######################
GET http://localhost:8000/users

####################
GET http://localhost:8000/api/users/2


######################

POST http://localhost:8000/city


####################
GET http://localhost:8000/api/state



####################
GET http://localhost:8000/api/category


####################
GET http://localhost:8000/api/restaurant


####################
GET http://localhost:8000/api/restaurantowner


####################
GET http://localhost:8000/api/orders


####################
GET http://localhost:8000/api/drivers


####################
GET http://localhost:8000/api/comments


####################
GET http://localhost:8000/api/menuitems


####################
GET http://localhost:8000/api/ordermenuitems


####################
GET http://localhost:8000/api/address


####################
GET http://localhost:8000/api/statuscatalog


####################
GET http://localhost:8000/api/orderstatus

















#
POST http://localhost:8000/api/users
Content-Type: application/json

{
    "id": 5,
    "name": "John",
    "contact_phone": "0798447783",
    "phone_verified": false,
    "email": "john@gmail.com",
    "email_verified": true,
    "password": "124rfcv",
    "created_at": "2015-07-03",
    "updated_at": "2015-07-13"
}



####################


####################


